//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_Store.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bookshop_DBEntities : DbContext
    {
        public Bookshop_DBEntities()
            : base("name=Bookshop_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_Category> TBL_Category { get; set; }
        public virtual DbSet<TBL_Entesharat> TBL_Entesharat { get; set; }
        public virtual DbSet<TBL_Images> TBL_Images { get; set; }
        public virtual DbSet<TBL_Product> TBL_Product { get; set; }
        public virtual DbSet<TBL_Translator> TBL_Translator { get; set; }
        public virtual DbSet<TBL_User> TBL_User { get; set; }
        public virtual DbSet<TBL_Comments> TBL_Comments { get; set; }
        public virtual DbSet<TBL_Orderdetail> TBL_Orderdetail { get; set; }
        public virtual DbSet<TBL_Order> TBL_Order { get; set; }
        public virtual DbSet<TBL_Writer> TBL_Writer { get; set; }
    }
}
