//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Comments
    {
        public int Comment_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public int Product_ID { get; set; }
        public string Comment_Content { get; set; }
        public Nullable<int> Comment_Status { get; set; }
    
        public virtual TBL_Product TBL_Product { get; set; }
        public virtual TBL_User TBL_User { get; set; }
    }
}
