//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Writer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Writer()
        {
            this.TBL_Product = new HashSet<TBL_Product>();
        }
    
        public int ID { get; set; }
        public string FullName { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> Birthday { get; set; }
        public Nullable<int> Deathdate { get; set; }
        public string Writer_Content { get; set; }
        public string Image { get; set; }
        public string Image_Thumbnail { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Iranian { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Product> TBL_Product { get; set; }
    }
}
