//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Orderdetail
    {
        public int Detailid { get; set; }
        public Nullable<int> Orderid { get; set; }
        public Nullable<int> Productid { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual TBL_Product TBL_Product { get; set; }
        public virtual TBL_Order TBL_Order { get; set; }
    }
}
